# --- CONSTANTS ---
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (50, 200, 50)
RED = (200, 50, 50)
BLUE = (50, 50, 200)
GRAY = (100, 100, 100)
DARK_GREY = (30, 30, 30)

# Game States
STATE_MENU = "MENU"  # Main Menu
STATE_ROSTER = "ROSTER"  # Turtle Roster Management
STATE_RACE = "RACE"
STATE_RACE_RESULT = "RACE_RESULT"
STATE_SHOP = "SHOP"
STATE_BREEDING = "BREEDING"
STATE_PROFILE = "PROFILE"  # Turtle Profile View (new)
STATE_VOTING = "VOTING"  # Design Voting View (new)
STATE_SETTINGS = "SETTINGS"  # Settings Menu (new)

# Gameplay Constants
TRACK_LENGTH_LOGIC = 1500
TRACK_LENGTH_PIXELS = 700
RECOVERY_RATE = 0.1
RECOVERY_THRESHOLD = 0.5
TERRAIN_DIFFICULTY = 1.0

# Economy
COST_TURTLE = 50
COST_REFRESH = 5
REWARD_1ST = 50
REWARD_2ND = 25
REWARD_3RD = 10

# Betting (MVP)
BET_LEVELS = [0, 5, 10]
